export interface Question {
  id: string;
  questionText: string;
  answers: Array<{ label: string; content: string }>;
  correctAnswers: string[]; // ['A'] hoặc ['A', 'B']
}

// Dictionary để sửa lỗi chính tả
const spellingCorrections: Record<string, string> = {
  // Common words - basic
  "cac": "các",
  "nao": "nào",
  "phai": "phải",
  "Phai": "Phải",
  "noi": "nói",
  "Noi": "Nói",
  "ve": "về",
  "Ve": "Về",
  "cua": "của",
  "Cua": "Của",
  "nen": "nền",
  "Nen": "Nền",
  "la": "là",
  "La": "Là",
  "chi biết": "chỉ biết",
  "chi thấy": "chỉ thấy",
  "Chi biết": "Chỉ biết",
  "Chi thấy": "Chỉ thấy",
  "sau đay": "sau đây",
  "Sau đay": "Sau đây",
  "tính chat": "tính chất",
  "Tính chat": "Tính chất",
  "vấn đe": "vấn đề",
  "Vấn đe": "Vấn đề",
  "nang cao": "nâng cao",
  "trinh độ": "trình độ",
  "dan toc": "dân tộc",
  "khoa hoc": "khoa học",
  "dai chung": "đại chúng",
  "cung": "cũng",
  "mot": "một",
  "mat tran": "mặt trận",
  "xay dung": "xây dựng",
  "duc tin": "đức tin",
  "vung chac": "vững chắc",
  "moi": "mới",
  "cong bo": "công bố",
  "chi biết": "chỉ biết",
  "thu ven": "thu vén",
  "rieng": "riêng",
  "minh": "mình",
  "chi thay": "chỉ thấy",
  "cong lao": "công lao",
  "quen": "quên",
  "vị k": "vị kỷ",
  "tu ban": "tư bản",
  "phong cach": "phong cách",
  "tieu tu san": "tiểu tư sản",
  "van hoa": "văn hóa",
  "doi song": "đời sống",
  "tinh than": "tinh thần",
  "xa hoi": "xã hội",
  "thuoc": "thuộc",
  "yeu to": "yếu tố",
  "Kien truc": "Kiến trúc",
  "thuong tang": "thượng tầng",
  "co so": "cơ sở",
  "ha tang": "hạ tầng",
  "Phuong thuc": "Phương thức",
  "san xuat": "sản xuất",
  "Luc luong": "Lực lượng",
  "neu cao": "nêu cao",
  "chu nghia": "chủ nghĩa",
  "tap the": "tập thể",
  "trừ bò": "trừ bỏ",
  "van de": "vấn đề",
  "vi ky": "vị kỷ",
  "loài người": "loài người",
  "sang tao": "sáng tạo",
  "phat minh": "phát minh",
  "ngon ngu": "ngôn ngữ",
  "chu viet": "chữ viết",
  "dao duc": "đạo đức",
  "đạở": "đạo",
  "Đạở": "Đạo",
  "đạở đức": "đạo đức",
  "Đạở đức": "Đạo đức",
  "Mình": "Minh",
  "Hồ Chí Mình": "Hồ Chí Minh",
  "Hồ Chí mình": "Hồ Chí Minh",
  "phap luat": "pháp luật",
  "ton giao": "tôn giáo",
  "van hoc": "văn học",
  "nghe thuat": "nghệ thuật",
  "cong cu": "công cụ",
  "sinh hoat": "sinh hoạt",
  "hang ngay": "hằng ngày",
  "ve": "về",
  "mac": "mặc",
  "an": "ăn",
  "phuong thuc": "phương thức",
  "su dung": "sử dụng",
  "le sinh ton": "lẽ sinh tồn",
  "muc dich": "mục đích",
  "cuoc song": "cuộc sống",
  "nhu cau": "nhu cầu",
  "phat trien": "phát triển",
  "sinh ton": "sinh tồn",
  "khang dinh": "khẳng định",
  "nguoi cach mang": "người cách mạng",
  "nen tang": "nền tảng",
  "hoan thanh": "hoàn thành",
  "nhiem vu": "nhiệm vụ",
  "ve vang": "vẻ vang",
  "Tri tue": "Trí tuệ",
  "Phuong phap": "Phương pháp",
  "Dao duc": "Đạo đức",
  "Y chi": "Ý chí",
  "khuyet diem": "khuyết điểm",
  "thanh nien": "thanh niên",
  "chuong": "chuộng",
  "hinh thuc": "hình thức",
  "tu do": "tự do",
  "loi": "lợi",
  "huong thu": "hưởng thụ",
  "Luan diem": "Luận điểm",
  "Doan ket": "Đoàn kết",
  "dai doan ket": "đại đoàn kết",
  "Thanh cong": "Thành công",
  "dai thanh cong": "đại thành công",
  "Chu tich": "Chủ tịch",
  "trich": "trích",
  "tac pham": "tác phẩm",
  "Bai noi chuyen": "Bài nói chuyện",
  "tai": "tại",
  "trong": "trong",
  "buoi": "buổi",
  "Be mac": "Bế mạc",
  "Dai hoi": "Đại hội",
  "thanh lap": "thành lập",
  "Mat tran": "Mặt trận",
  "To Quoc": "Tổ Quốc",
  "Viet Nam": "Việt Nam",
  "Hoi nghi": "Hội nghị",
  "mo rong": "mở rộng",
  "Uy ban": "Ủy ban",
  "lan thu": "lần thứ",
  "noi chuyen": "nói chuyện",
  "voi": "với",
  "can bo": "cán bộ",
  "chien si": "chiến sĩ",
  "Dai doan": "Đại đoàn",
  "Quan Tien Phong": "Quân Tiên Phong",
  "chuan muc": "chuẩn mực",
  "tu tuong": "tư tưởng",
  "Trung": "Trung",
  "nuoc": "nước",
  "hieu": "hiếu",
  "dan": "dân",
  "dong bao": "đồng bào",
  "cach mang": "cách mạng",
  "co may": "có mấy",
  "chuc nang": "chức năng",
  "chu yeu": "chủ yếu",
  "tuyet doi": "tuyệt đối",
  "trung thanh": "trung thành",
  "su nghiep": "sự nghiệp",
  "dung nuoc": "dựng nước",
  "giu nuoc": "giữ nước",
  "con duong": "con đường",
  "di len": "đi lên",
  "dat nuoc": "đất nước",
  "suot doi": "suốt đời",
  "phan dau": "phấn đấu",
  "Dang": "Đảng",
  "Nha nuoc": "Nhà nước",
  "Dan toc": "Dân tộc",
  "quan chung": "quần chúng",
  "vai tro": "vai trò",
  "the nao": "thế nào",
  "goc": "gốc",
  "nguoi": "người",
  "lanh dao": "lãnh đạo",
  "can benh": "căn bệnh",
  "vi trung": "vi trùng",
  "rat doc": "rất độc",
  "de ra": "đẻ ra",
  "hang tram": "hàng trăm",
  "benh": "bệnh",
  "nguy hiem": "nguy hiểm",
  "ca nhan": "cá nhân",
  "Thoi quan": "Thói quen",
  "truyen thong": "truyền thống",
  "lac hau": "lạc hậu",
  "tham o": "tham ô",
  "lang phi": "lãng phí",
  "duoc vi": "được ví",
  "nhu": "như",
  "giac": "giặc",
  "Ngoai xam": "Ngoại xâm",
  "Noi xam": "Nội xâm",
  "My": "Mỹ",
  "dot": "dốt",
  "quan diem": "quan điểm",
  "Cong san": "Cộng sản",
  "dai bieu": "đại biểu",
  "toan quoc": "toàn quốc",
  "ket qua": "kết quả",
  "van dung": "vận dụng",
  "ke thua": "kế thừa",
  "gia tri": "giá trị",
  "Mac": "Mác",
  "Lenin": "Lênin",
  "dieu kien": "điều kiện",
  "cu the": "cụ thể",
  "nuoc ta": "nước ta",
  "dua ra": "đưa ra",
  "dinh nghia": "định nghĩa",
  "toan dien": "toàn diện",
  "sau sac": "sâu sắc",
  "nhung": "những",
  "co ban": "cơ bản",
  "Tu nao": "Từ nào",
  "con thieu": "còn thiếu",
  "dau": "dấu",
  "He thong": "Hệ thống",
  "luan diem": "luận điểm",
  "Vận dụng": "Vận dụng",
  "can phai": "cần phải",
  "nam vung": "nắm vững",
  "lich su": "lịch sử",
  "the gioi": "thế giới",
  "Khai niem": "Khái niệm",
  "neu len": "nêu lên",
  "KHONG": "KHÔNG",
  "bao gom": "bao gồm",
  "noi dung": "nội dung",
  "sau day": "sau đây",
  "Ban chat": "Bản chất",
  "Nguon goc": "Nguồn gốc",
  "ly luan": "lý luận",
  "Ket cau": "Kết cấu",
  "Trong": "Trong",
  "duoc xem": "được xem",
  "la": "là",
  "nhom": "nhóm",
  "hoc thuyet": "học thuyết",
  "Ho Chi Minh": "Hồ Chí Minh",
  "chi ra": "chỉ ra",
  "nguyen tac": "nguyên tắc",
  "hoat dong": "hoạt động",
  "theo": "theo",
  "hiep thuong": "hiệp thương",
  "dan chu": "dân chủ",
  "dan quyen": "dân quyền",
  "nhan dan": "nhân dân",
  "dac diem": "đặc điểm",
  "phap quyen": "pháp quyền",
  "thuc hien": "thực hiện",
  "Su": "Sự",
  "doi": "đối",
  "hop hien": "hợp hiến",
  "hop phap": "hợp pháp",
  "chu the": "chủ thể",
  "quyen luc": "quyền lực",
  "khach the": "khách thể",
  "nguon goc": "nguồn gốc",
  "suc manh": "sức mạnh",
  "dong tinh": "đồng tình",
  "ung ho": "ủng hộ",
  "da so": "đa số",
  "lao dong": "lao động",
  "doi tien phong": "đội tiền phong",
  "giai cap": "giai cấp",
  "vo san": "vô sản",
  "duoc": "được",
  "C. Mac": "C. Mác",
  "Ph. Angghen": "Ph. Ăngghen",
  "V.I. Lenin": "V.I. Lênin",
  "cam quyen": "cầm quyền",
  "vi vay": "vì vậy",
  "moi": "mỗi",
  "dang vien": "đảng viên",
  "Het long": "Hết lòng",
  "phuc vu": "phục vụ",
  "cong nhan": "công nhân",
  "Ra suc": "Ra sức",
  "hoc tap": "học tập",
  "trau doi": "trau dồi",
  "chuyen mon": "chuyên môn",
  "Thuc su": "Thực sự",
  "tham nhuan": "thấm nhuần",
  "can": "cần",
  "kiem": "kiệm",
  "liem": "liêm",
  "chinh": "chính",
  "chi cong": "chí công",
  "vo tu": "vô tư",
  "Xay dung": "Xây dựng",
  "khoi": "khối",
  "Noi dung": "Nội dung",
  "quy bau": "quý báu",
  "cot loi": "cốt lõi",
  "yeu nuoc": "yêu nước",
  "toan dan": "toàn dân",
  "chi la": "chỉ là",
  "sach luoc": "sách lược",
  "nhat thoi": "nhất thời",
  "nhan to": "nhân tố",
  "quyet dinh": "quyết định",
  "hang dau": "hàng đầu",
  "dua": "đưa",
  "den": "đến",
  "thang loi": "thắng lợi",
  "phan anh": "phản ánh",
  "dieu gi": "điều gì",
  "vi the": "vị thế",
  "hieu luc": "hiệu lực",
  "phap ly": "pháp lý",
  "manh me": "mạnh mẽ",
  "quan ly": "quản lý",
  "bang": "bằng",
  "Hien phap": "Hiến pháp",
  "chu trong": "chú trọng",
  "thuc tien": "thực tiễn",
  "Qua": "Qua",
  "to chuc": "tổ chức",
  "bo may": "bộ máy",
  "Bang": "Bằng",
  "cong tac": "công tác",
  "kiem tra": "kiểm tra",
  "giao phai": "giáo phái",
  "day to": "đầy tớ",
  "khong co": "không có",
  "nghia la": "nghĩa là",
  "toi to": "tôi tớ",
  "toi doi": "tôi đòi",
  "hay": "hay",
  "theo uoi": "theo đuổi",
  "ma": "mà",
  "Hieu": "Hiểu",
  "danh gia": "đánh giá",
  "dung": "đúng",
  "nham": "nhằm",
  "dem lai": "đem lại",
  "quyen": "quyền",
  "loi ich": "lợi ích",
  "Tan tam": "Tận tâm",
  "tan luc": "tận lực",
  "phung su": "phụng sự",
  "ra suc": "ra sức",
  "tro thanh": "trở thành",
  "quan": "quan",
  "Dam bao": "Đảm bảo",
  "moi": "mọi",
  "nguyen vong": "nguyện vọng",
  "lang nghe": "lắng nghe",
  "dap ung": "đáp ứng",
  "Pham chat": "Phẩm chất",
  "duoi day": "dưới đây",
  "chu quan": "chủ quan",
  "dan den": "dẫn đến",
  "hinh thanh": "hình thành",
  "trai tim": "trái tim",
  "thuong": "thương",
  "san sang": "sẵn sàng",
  "chiu dung": "chịu đựng",
  "hy sinh": "hy sinh",
  "Tư duy": "Tư duy",
  "doc lap": "độc lập",
  "tu chu": "tự chủ",
  "dau oc": "đầu óc",
  "phe phan": "phê phán",
  "tinh tuong": "tinh tường",
  "sang suot": "sáng suốt",
  "Ban linh": "Bản lĩnh",
  "kien dinh": "kiên định",
  "luon": "luôn",
  "tin": "tin",
  "khiem ton": "khiêm tốn",
  "binh di": "bình dị",
  "ham": "ham",
  "hoc hoi": "học hỏi",
  "cong danh": "công danh",
  "phu quy": "phú quý",
  "Giai doan": "Giai đoạn",
  "tim thay": "tìm thấy",
  "cuu nuoc": "cứu nước",
  "giai phong": "giải phóng",
  "so sanh": "so sánh",
  "nhan dinh": "nhận định",
  "nhu the nao": "như thế nào",
  "Chang khac": "Chẳng khác",
  "gi": "gì",
  "nhau": "nhau",
  "Khac": "Khác",
  "Rat": "Rất",
  "dac biet": "đặc biệt",
  "Giong": "Giống",
  "Bao": "Báo",
  "Le Paria": "Le Paria",
  "Nguyen Ai Quoc": "Nguyễn Ái Quốc",
  "dong sang lap": "đồng sáng lập",
  "ra so": "ra số",
  "dau tien": "đầu tiên",
  "khi nao": "khi nào",
  "duoc coi": "được coi",
  "linh hon": "linh hồn",
  "cuoc": "cuộc",
  "khang chien": "kháng chiến",
  "chong": "chống",
  "Phap": "Pháp",
  "giai doan": "giai đoạn",
  "mat": "mất",
  "bao nhieu": "bao nhiêu",
  "nam": "năm",
  "bon ba": "bôn ba",
  "nuoc ngoai": "nước ngoài",
  "tim duong": "tìm đường",
  "Tu tuong": "Tư tưởng",
  "anh huong": "ảnh hưởng",
  "Tư duy": "Tư duy",
  "hanh dong": "hành động",
  "ung xu": "ứng xử",
  "Phat giao": "Phật giáo",
  "Hoi giao": "Hồi giáo",
  "An Do giao": "Ấn Độ giáo",
  "Kito giao": "Kitô giáo",
  "bo sung": "bổ sung",
  "hoan thien": "hoàn thiện",
  "phuong Tay": "phương Tây",
  "truoc": "trước",
  "khi": "khi",
  "ra di": "ra đi",
  "Truyen thong": "Truyền thống",
  "tien bo": "tiến bộ",
  "Duc": "Đức",
  "thuc chung": "thực chứng",
  "Hoa Ky": "Hoa Kỳ",
  "Triet hoc": "Triết học",
  "nguon goc": "nguồn gốc",
  "lac quan": "lạc quan",
  "yeu doi": "yêu đời",
  "niem tin": "niềm tin",
  "chinh nghia": "chính nghĩa",
  "ban than": "bản thân",
  "nhan nghia": "nhân nghĩa",
  "thuy chung": "thủy chung",
  "doan ket": "đoàn kết",
  "co ket": "cố kết",
  "cong dong": "cộng đồng",
  "hoa binh": "hòa bình",
  "quoc te": "quốc tế",
  "dam bao": "đảm bảo",
  "thoi dai": "thời đại",
  "nhan loai": "nhân loại",
  "dai chung": "đại chúng",
  "cac nuoc": "các nước",
  "dat quan he": "đặt quan hệ",
  "ngoai giao": "ngoại giao",
  "Gan dan": "Gần dân",
  "y kien": "ý kiến",
  "ngoai dang": "ngoài đảng",
  "moi nguoi": "mọi người",
  "tang lop": "tầng lớp",
  "Vi sao": "Vì sao",
  "lai": "lại",
  "toan dan toc": "toàn dân tộc",
  "phai duoc": "phải được",
  "xac dinh": "xác định",
  "khong chi": "không chỉ",
  "la": "là",
  "khau hieu": "khẩu hiệu",
  "chien luoc": "chiến lược",
  "ma con": "mà còn",
  "quan triet": "quán triệt",
  "tat ca": "tất cả",
  "linh vuc": "lĩnh vực",
  "tu": "từ",
  "duong loi": "đường lối",
  "chu truong": "chủ trương",
  "chinh sach": "chính sách",
  "toi": "tới",
  "van dong": "vận động",
  "thuyet phuc": "thuyết phục",
  "huong dan": "hướng dẫn",
  "giao duc": "giáo dục",
  "giac ngo": "giác ngộ",
  "lien lac": "liên lạc",
  "deu phai": "đều phải",
  "dem ra": "đem ra",
  "cho": "cho",
  "thanh vien": "thành viên",
  "cung": "cùng",
  "ban bac": "bàn bạc",
  "cong khai": "công khai",
  "de": "để",
  "di den": "đi đến",
  "nhat tri": "nhất trí",
  "loai tru": "loại trừ",
  "su": "sự",
  "ap dat": "áp đặt",
  "hay": "hay",
  "con": "còn",
  "khac": "khác",
  "nua": "nữa",
  "Dan chu": "Dân chủ",
  "tu nguyen": "tự nguyện",
  "Chuyen quyen": "Chuyên quyền",
  "doc doan": "độc đoán",
  "Khong": "Không",
  "Doi voi": "Đối với",
  "phong trao": "phong trào",
  "cong san": "cộng sản",
  "giuong cao": "giương cao",
  "ngon co": "ngọn cờ",
  "gan lien": "gắn liền",
  "thong nhat": "thống nhất",
  "tren": "trên",
  "co ly": "có lý",
  "co tinh": "có tình",
  "co nghia": "có nghĩa",
  "Khau hieu": "Khẩu hiệu",
  "toan the gioi": "toàn thế giới",
  "bi": "bị",
  "ap buc": "áp bức",
  "Hay": "Hãy",
  "chon": "chọn",
  "phuong an": "phương án",
  "tra loi": "trả lời",
  "dung nhat": "đúng nhất",
  "tap hop": "tập hợp",
  "luc luong": "lực lượng",
  "vao": "vào",
  "lam gi": "làm gì",
  "dung dan": "đúng đắn",
  "phu hop": "phù hợp",
  "tung": "từng",
  "doi tuong": "đối tượng",
  "Vua": "Vừa",
  "Cham lo": "Chăm lo",
  "vat chat": "vật chất",
  "Dieu kien": "Điều kiện",
  "yeu": "yêu",
  "thien nhien": "thiên nhiên",
  "con nguoi": "con người",
  "nhan ai": "nhân ái",
  "cho rang": "cho rằng",
  "chu y": "chú ý",
  "diem gi": "điểm gì",
  "Phai": "Phải",
  "tranh": "tránh",
  "phe binh": "phê bình",
  "xoa bo": "xóa bỏ",
  "het": "hết",
  "thanh kien": "thành kiến",
  "va": "và",
  "giup do": "giúp đỡ",
  "lan": "lẫn",
  "tien bo": "tiến bộ",
  "Đau": "Đâu",
  "Nghiem tuc": "Nghiêm túc",
  "hop tac": "hợp tác",
  "That tha": "Thật thà",
  "San sang": "Sẵn sàng",
  "Tich cuc": "Tích cực",
  "tu san": "tư sản",
  "dan quyen": "dân quyền",
  "tho dia": "thổ địa",
  "Tien hanh": "Tiến hành",
  "dong thoi": "đồng thời",
  "tinh chat": "tính chất",
  "thuoc dia": "thuộc địa",
  "Giai phong": "Giải phóng",
  "nhan loai": "nhân loại",
  "vach ra": "vạch ra",
  "mau thuan": "mâu thuẫn",
  "Nhan dan": "Nhân dân",
  "thuc dan": "thực dân",
  "phong kien": "phong kiến",
  "dia chu": "địa chủ",
  "de quoc": "đế quốc",
  "de co the": "để có thể",
  "tan dung": "tận dụng",
  "thoi co": "thời cơ",
  "vuot qua": "vượt qua",
  "thach thuc": "thách thức",
  "nhan thuc": "nhận thức",
  "tap trung": "tập trung",
  "Kien dinh": "Kiên định",
  "Con nguoi": "Con người",
  "hieu": "hiểu",
  "tac phong": "tác phong",
  "Nhung": "Những",
  "nam": "nằm",
  "y thuc": "ý thức",
  "Cham": "Chăm",
  "Thuc chat": "Thực chất",
  "Xoa bo": "Xóa bỏ",
  "boc lot": "bóc lột",
  "tinh cach": "tính cách",
  "thong tri": "thống trị",
  "Tieu diet": "Tiêu diệt",
  "thu tieu": "thủ tiêu",
  "triet tieu": "triệt tiêu",
  "cu": "cũ",
  "boi": "bởi",
  "Con duong": "Con đường",
  "bat bao dong": "bất bạo động",
  "bao luc": "bạo lực",
  "on hoa": "ôn hòa",
  "dau tranh": "đấu tranh",
  "Dau": "Đâu",
  "cua": "của",
  "Giu vung": "Giữ vững",
  "dong thoi": "đồng thời",
  "ton trong": "tôn trọng",
  "kinh trong": "kính trọng",
  "quoc gia": "quốc gia",
  "vung": "vững",
  "nhung": "nhưng",
  "phu thuoc": "phụ thuộc",
  "thang loi": "thắng lợi",
  "chinh quoc": "chính quốc",
  "bien phap": "biện pháp",
  "nhat": "nhất",
  "Dem": "Đem",
  "cua dan": "của dân",
  "tai dan": "tài dân",
  "suc dan": "sức dân",
  "lam loi": "làm lợi",
  "ban phat": "ban phát",
  "tu": "từ",
  "tren": "trên",
  "xuong": "xuống",
  "dua": "dựa",
  "tu luc": "tự lực",
  "canh sinh": "cánh sinh",
  "suc": "sức",
  "chinh": "chính",
  "Khong co gi": "Không có gì",
  "quy hon": "quý hơn",
  "dang": "đang",
  "tien hanh": "tiến hành",
  "chien tranh": "chiến tranh",
  "the luc": "thế lực",
  "Thuc dan": "Thực dân",
  "Phat xit": "Phát xít",
  "Nhat": "Nhật",
  "De quoc": "Đế quốc",
  "Phong kien": "Phong kiến",
  // Special cases - phrases
  "luan điểm": "luận điểm",
  "Luan điểm": "Luận điểm",
  "Đời sống moi": "Đời sống mới",
  "Chủ nghĩa vị k": "Chủ nghĩa vị kỷ",
  "chủ nghĩa vị k": "chủ nghĩa vị kỷ",
  "trừ bò": "trừ bỏ",
  "Trừ bò": "Trừ bỏ",
  "đoi song": "đời sống",
  "Đoi song": "Đời sống",
  "tinh than": "tinh thần",
  "Tinh than": "Tinh thần",
  "lào": "lao",
  "Lào": "Lao",
};

// Function để sửa lỗi chính tả
export function fixSpelling(text: string): string {
  if (!text) return text;
  
  let fixed = text;
  
  // Fix duplicate characters first (to avoid issues like "vị kỷỷ")
  fixed = fixed.replace(/kỷỷ+/g, 'kỷ');
  fixed = fixed.replace(/kỳỳ+/g, 'kỳ');
  
  // Sắp xếp theo độ dài giảm dần để match từ dài trước
  const sortedKeys = Object.keys(spellingCorrections).sort((a, b) => b.length - a.length);
  
  for (const key of sortedKeys) {
    // Use word boundaries for single words, but not for phrases
    const isPhrase = key.includes(' ');
    const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // For phrases or words that might be part of other words, don't use word boundary
    // For single words that should be exact matches, use word boundary
    const useWordBoundary = !isPhrase && !['lào', 'Lào'].includes(key);
    const pattern = useWordBoundary
      ? new RegExp(`\\b${escapedKey}\\b`, 'gi')
      : new RegExp(escapedKey, 'gi');
    
    fixed = fixed.replace(pattern, (match) => {
      // Giữ nguyên case của chữ cái đầu
      if (match[0] === match[0].toUpperCase()) {
        return spellingCorrections[key].charAt(0).toUpperCase() + spellingCorrections[key].slice(1);
      }
      return spellingCorrections[key];
    });
  }
  
  return fixed;
}

// Parse file txt thành array of questions
export function parseExamFile(content: string): Question[] {
  const lines = content.split('\n').map(line => line.trim());
  const questions: Question[] = [];
  
  let i = 0;
  let questionIndex = 1;
  
  while (i < lines.length) {
    // Skip empty lines at the start
    while (i < lines.length && !lines[i]) {
      i++;
    }
    
    if (i >= lines.length) break;
    
    // Collect question text (can be multiple lines)
    const questionLines: string[] = [];
    while (i < lines.length && lines[i] && !/^[A-Z]\.\s/.test(lines[i])) {
      questionLines.push(lines[i]);
      i++;
    }
    
    if (questionLines.length === 0) {
      i++;
      continue;
    }
    
    const questionText = fixSpelling(questionLines.join(' '));
    
    // Collect answers
    const answers: Array<{ label: string; content: string }> = [];
    while (i < lines.length && /^[A-Z]\.\s/.test(lines[i])) {
      const match = lines[i].match(/^([A-Z])\.\s(.+)$/);
      if (match) {
        const label = match[1];
        const content = fixSpelling(match[2]);
        answers.push({ label, content });
      }
      i++;
      
      // Skip empty line after answer
      if (i < lines.length && !lines[i]) {
        i++;
      }
    }
    
    // Find correct answer(s)
    const correctAnswers: string[] = [];
    while (i < lines.length) {
      if (!lines[i]) {
        i++;
        continue;
      }
      
      // Check if this line contains answer (A, B, C, D or A,B,C)
      const answerMatch = lines[i].match(/^([A-Z](?:,\s*[A-Z])*)\s*$/);
      if (answerMatch) {
        const answerStr = answerMatch[1];
        const answerLabels = answerStr.split(',').map(a => a.trim());
        correctAnswers.push(...answerLabels);
        i++;
        break;
      }
      
      // If we hit another question, break
      if (lines[i] && !/^[A-Z]\.\s/.test(lines[i]) && !answerMatch) {
        break;
      }
      
      i++;
    }
    
    if (questionText && answers.length > 0 && correctAnswers.length > 0) {
      questions.push({
        id: `q${questionIndex}`,
        questionText,
        answers,
        correctAnswers,
      });
      questionIndex++;
    }
  }
  
  return questions;
}
